apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: helm/cloudnative-pg/charts/cloudnative-pg
  contents:
  - path: .
    git:
      url: https://github.com/giantswarm/cloudnative-pg-upstream
      ref: cloudnative-pg-v0.24.0
    includePaths:
      - charts/cloudnative-pg/**/*
    newRootPath: charts/cloudnative-pg
