apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: gs-postgresql
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
  labels:
    {{- include "cloudnative-pg.labels" . | nindent 4 }}
spec:
  images:
    - major: 16
      image: quay.io/giantswarm/postgresql-cnpg:16.2
